### ISSUE TITLE
The hints in super-hint-rg are misaligned

### ISSUE THREAD

**Issue by yonta** [eval-exec/super-hint.el#4]
I tried using super-hint-rg with minimal settings.
Unlike in the README, the super-hints are displayed in the upper-right corner of the buffer, not on the left of each line.
Is this the correct behavior?

### enable super-hint-rg

![image](https://github.com/user-attachments/assets/ed7ecfb9-a3f9-46be-af9c-1b3384186976)

### disable super-hint-rg

![image](https://github.com/user-attachments/assets/4c41fedd-2e9f-4347-b971-991d80e86102)

## Minimal init.el

```elisp
;; load path for rg
(let ((default-directory  "~/.config/emacs/elpa/"))
  (normal-top-level-add-to-load-path '("."))
  (normal-top-level-add-subdirs-to-load-path))

(use-package super-hint
  :load-path "~/.config/emacs/elpa/super-hint/"
  :config
  (require 'rg)
  (require 'super-hint-rg)
  (super-hint-enable-rg)
  )
```

**Comment by eval-exec** [comment]
It's not expected behavior, please try to enable `(which-function-mode t)`?

**Comment by eval-exec** [comment]
When you execute `rg-*` related command after `(super-hint-enable-rg)`, did you feel lag or pause?

**Comment by yonta** [comment]
Oooops.
That's correct. I didn't read the README carefully enough.

Thanks！

**Comment by yonta** [comment]
Yes, when I executed rg-project and there were many search matches, I noticed a slight lag when super-hint updated the display.

**Comment by yonta** [comment]
As I was testing, it seems that rg first displays all the results, and then converts them into the super-hint format.
Especially when there are thousands of matches, it feels like the conversion process takes a long time.

I suspect this might be due to the overhead of which-function-mode itself.
Setting a limit on the number of search results for super-hint to run on might be a good idea.

**Comment by eval-exec** [comment]
> As I was testing, it seems that rg first displays all the results, and then converts them into the super-hint format. Especially when there are thousands of matches, it feels like the conversion process takes a long time.
> 
> I suspect this might be due to the overhead of which-function-mode itself. Setting a limit on the number of search results for super-hint to run on might be a good idea.

Agree. Do you interesting to submit a PR? Or do you interested to other customization to improve super-hint.el, welcome! :blue_heart:

**Comment by eval-exec** [comment]
> As I was testing, it seems that rg first displays all the results, and then converts them into the super-hint format. Especially when there are thousands of matches, it feels like the conversion process takes a long time.
> 
> I suspect this might be due to the overhead of which-function-mode itself. Setting a limit on the number of search results for super-hint to run on might be a good idea.

What programming language of file did you run `rg-*`? 
I tested `which-function-mode` is fast on `tree-sitter` supported files, like `rust-ts-mode`, `go-ts-mode`. 
Some files(`elisp file not support tree-sitter`), then which-function is slow, cause super-hint slow.

**Comment by yonta** [comment]
I was testing it with Elisp (Emacs source code).
Indeed, when I tried it with ruby-ts-mode, it became much faster.
