### ISSUE TITLE
error in process sentinel: super-hint-which-function: Wrong type argument: wholenump, nil 

### ISSUE THREAD

**Issue by getong** [eval-exec/super-hint.el#6]
error msg:
```
error in process sentinel: super-hint-which-function: Wrong type argument: wholenump, nil
error in process sentinel: Wrong type argument: wholenump, nil
```
config:
```
;; need by super-hint
(use-package rg
  :straight t
  :config
  (grep-apply-setting 'grep-template "rg --no-heading -H -uu -g <F> <R> <D>")
  :bind ("C-c g" . rg)
  )

(use-package super-hint
  :straight (:host github :repo "eval-exec/super-hint.el")
  :config
  (require 'rg)
  (require 'super-hint-rg)
  (super-hint-enable-rg) ;; then M-x rg-project to enjoy super-hint

  (require 'super-hint-xref)
  (super-hint-enable-xref) ;; then M-x xref-find-references to enjoy super-hint
  (which-function-mode t)) ;; need open which-function mode
```

screenshot
<img width="1201" alt="image" src="https://github.com/user-attachments/assets/ffeef02a-93a0-481a-94fa-2c21ed6ad9e0">
disable super-hint package
<img width="793" alt="image" src="https://github.com/user-attachments/assets/1fa6dc32-83ea-4a35-b9fe-688c8bf8e729">

**Comment by eval-exec** [comment]
Does `which-function-mode` is t in your emacs lisp mode?

**Comment by getong** [comment]
see my config, it is set to t.

**Comment by eval-exec** [comment]
How about remove `--no-heading ` in `grep-apply-setting`'s config?

**Comment by eval-exec** [comment]
Could you retry after removing `  (grep-apply-setting 'grep-template "rg --no-heading -H -uu -g <F> <R> <D>")`?

**Comment by getong** [comment]
<img width="1952" alt="image" src="https://github.com/user-attachments/assets/782a6747-62da-4991-8296-b2b652b41550">

error still occurs

**Comment by eval-exec** [comment]
Could you click `...` in the `/opt/homebrew/bin/rg [...]`, I want to know the full rg command arguments.

**Comment by getong** [comment]
```
/opt/homebrew/bin/rg --color=always --colors=match:fg:red --colors=path:fg:magenta --colors=line:fg:green --colors=column:none -n --column -i --heading --no-config --type=elisp -e use-package .
```

**Comment by eval-exec** [comment]
Could you retry it in a python/go/c file buffer?

**Comment by eval-exec** [comment]
@getong I notice your rg result buffer have no `File: `.
In my rg result buffer, I have `File: ` before file path:
![image](https://github.com/user-attachments/assets/856fd90a-974e-4955-92ff-bea092e70bfe)

What rg command did you execute to get rg-result. (I executed `M-x rg-project` to get the rg result)

**Comment by getong** [comment]
```
$ brew info ripgrep
==> ripgrep: stable 14.1.1 (bottled), HEAD
Search tool like grep and The Silver Searcher
https://github.com/BurntSushi/ripgrep
Installed
/opt/homebrew/Cellar/ripgrep/14.1.1 (14 files, 6MB) *
  Poured from bottle on 2024-09-18 at 14:17:31
From: https://mirrors.ustc.edu.cn/homebrew-core.git/Formula/r/ripgrep.rb
License: Unlicense
==> Dependencies
Build: asciidoctor ✘, pkg-config ✔, rust ✘
Required: pcre2 ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 27,189 (30 days), 47,932 (90 days), 184,967 (365 days)
install-on-request: 26,845 (30 days), 47,341 (90 days), 182,586 (365 days)
build-error: 0 (30 days)


➜  .emacs.d git:(main) ✗ ls -lhrt /opt/homebrew/bin/rg
lrwxr-xr-x  1 a  admin    31B  9 18 14:17 /opt/homebrew/bin/rg -> ../Cellar/ripgrep/14.1.1/bin/rg


➜  .emacs.d git:(main) ✗ ls /opt/homebrew/Cellar/ripgrep
14.1.1
➜  .emacs.d git:(main) ✗ ls /opt/homebrew/Cellar/ripgrep/14.1.1 
CHANGELOG.md         COPYING              INSTALL_RECEIPT.json LICENSE-MIT          README.md            bin                  etc                  sbom.spdx.json       share
➜  .emacs.d git:(main) ✗ ls /opt/homebrew/Cellar/ripgrep/14.1.1/bin 
rg
➜  .emacs.d git:(main) ✗ ls /opt/homebrew/Cellar/ripgrep/14.1.1/bin/rg
/opt/homebrew/Cellar/ripgrep/14.1.1/bin/rg
```

**Comment by getong** [comment]
I install  it with 
```
brew install ripgrep
```

**Comment by getong** [comment]
I think this error might be with rg package, it cannot jump to right file in the search result.

**Comment by eval-exec** [comment]
> <img alt="image" width="1952" src="https://private-user-images.githubusercontent.com/3949379/371742261-782a6747-62da-4991-8296-b2b652b41550.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTQ0MzEsIm5iZiI6MTcyNzUxNDEzMSwicGF0aCI6Ii8zOTQ5Mzc5LzM3MTc0MjI2MS03ODJhNjc0Ny02MmRhLTQ5OTEtODI5Ni1iMmI2NTJiNDE1NTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjhUMDkwMjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzE3NDg4ZGRhM2RkYTdhMjJjZDQ5ZTIxNmQ3YmFjY2VhZDgxNDQ1NjYyZDlmNGI5OGIwNmE0NTJjYTcyMzk0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mcOGNh9q0JWgRJeCaO27qbqT6A12Ubi1rm67sSKj5wA">
> error still occurs

Could you put cursor on rg's result buffer's "file name(`./init-flutter.el`)", execute `M-x describe-char`.

**Comment by getong** [comment]
```
             position: 313 of 27290 (1%), column: 4
            character: r (displayed as r) (codepoint 114, #o162, #x72)
              charset: ascii (ASCII (ISO646 IRV))
code point in charset: 0x72
               script: latin
               syntax: w 	which means: word
             category: .:Base, L:Strong L2R, a:ASCII, l:Latin, r:Roman
             to input: type "C-x 8 RET 72" or "C-x 8 RET LATIN SMALL LETTER R"
          buffer code: #x72
            file code: #x72 (encoded by coding system utf-8)
              display: by this font (glyph code):
    mac-ct:-*-Cascadia Code-regular-italic-normal-*-12-*-*-*-m-0-iso10646-1 (#x17E)

Character code properties: customize what to show
  name: LATIN SMALL LETTER R
  general-category: Ll (Letter, Lowercase)
  decomposition: (114) ('r')

There are text properties here:
  font-lock-face       (:foreground "#7F60A7")
  fontified            t
  xterm-color          t

[back]

```

**Comment by eval-exec** [comment]
Could you execute `M-x describe-variable major-mode` in rg's result buffer?

I suspect your rg's result buffer is not `#'rg-mode` ?

**Comment by getong** [comment]
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/1422e124-beff-4b29-980a-04e6869fca92">

**Comment by eval-exec** [comment]
😿 Not sure why super-hint.el isn't working as expected on your machine.

Could you execute `toggle-debug-on-error` to `t`, then do rg again, give me the elisp's error backtrace?

**Comment by getong** [comment]
I update my rg config
```
;; need by super-hint
(use-package rg
  :straight t
  :commands rg
  :custom
  (rg-command-line-flags '("--no-heading" "--line-number" "--column"))
  (rg-group-result nil)
  (rg-show-columns t)
  :config
  ;; C-c s, https://rgel.readthedocs.io/en/latest/usage.html
  (rg-enable-default-bindings)
  )

(use-package super-hint
  :straight (:host github :repo "eval-exec/super-hint.el")
  :config
  (require 'rg)
  (require 'super-hint-rg)
  (super-hint-enable-rg) ;; then M-x rg-project to enjoy super-hint

  (require 'super-hint-xref)
  (super-hint-enable-xref) ;; then M-x xref-find-references to enjoy super-hint
  (which-function-mode t)) ;; need open which-function mode
```
it works, but the display is still wrong:
<img width="1936" alt="image" src="https://github.com/user-attachments/assets/01faf5f5-32ec-45a5-832e-17ee6e70afb8">

no error msg now

**Comment by eval-exec** [comment]
Could you change `--no-heading` to `--heading` in Line 297's `rg-command-line-flags` , then retry?

**Comment by getong** [comment]
It differs nothing
<img width="1907" alt="image" src="https://github.com/user-attachments/assets/622498ae-dfa1-4027-96c4-13b2973eea49">

**Comment by eval-exec** [comment]
Could you set `rg-group-result` to `t`, then retry?

**Comment by getong** [comment]
<img width="1815" alt="image" src="https://github.com/user-attachments/assets/eb5152f4-fa94-4d93-930c-9a54619d8305">

with the `rg-group-result` set to `t`, the rg result cannot jump to the right file.
So I set it to nil

**Comment by eval-exec** [comment]
> with the rg-group-result set to t, the rg result cannot jump to the right file.

This's not expected. If you set `rg-group-result` to t, and `(super-hint-disable-rg)`, then re-execute  rg command, does the rg result can jump to the right file?

**Comment by getong** [comment]
<img width="1864" alt="image" src="https://github.com/user-attachments/assets/841413d7-e08c-4d34-a1bb-d52f1e132df8">

No, it cannot jump to the right file.

**Comment by eval-exec** [comment]
Could you execute `M-x describe-variable default-directory` in rg's result buffer?

**Comment by eval-exec** [comment]
That's really weird!

**Comment by getong** [comment]
```
default-directory is a variable defined in ‘C source code’.

Its value is "/Users/a/.emacs.d/elisp/"
Local in buffer *rg*; global value is nil

Name of default directory of current buffer.
It should be an absolute directory name; on GNU and Unix systems,
these names start with "/" or "~" and end with "/".
To interactively change the default directory, use the command ‘cd’.

  Automatically becomes permanently buffer-local when set.
  This variable is safe as a file local variable if its value
  satisfies the predicate ‘stringp’.
  Probably introduced at or before Emacs version 1.11.

[back]

```

**Comment by eval-exec** [comment]
In your minibuffer's prompt, I see `Find thie error in (default 408)`, it seems that emacs treat the line number(408) as filename.

**Comment by getong** [comment]
> In your minibuffer's prompt, I see `Find thie error in (default 408)`, it seems that emacs treat the line number(408) as filename.

Yes, it does.

**Comment by eval-exec** [comment]
Could you put cursor on the "408" in rg's result, then `M-: (get-text-property (point) 'compilation-message)`, what does it output?

**Comment by getong** [comment]
how to input this command?

**Comment by eval-exec** [comment]
You can : `M-x eval-expression RET (get-text-property (point) 'compilation-message)`

**Comment by eval-exec** [comment]
Please focus in rg's reuslt buffer, put cursor on the "408", then execute:
1. `M-x eval-expression RET (get-text-property (point) 'compilation-message) RET`
2. `M-x eval-expression RET (text-properties-at (point)) RET`

**Comment by getong** [comment]
it prints  nil in the minibuffer

**Comment by getong** [comment]
(text-properties-at (point)) returns (fontified t)

**Comment by eval-exec** [comment]
> it prints nil in the minibuffer

It's weried. It should print many things. I guess in your configuration, something affect rg's result buffer's behavior.

Could you reproduce it by a minimal configuration file, launch emacs by `emacs -Q`, and  only use `rg.el` and `super-hint.el` to reproduce the bug?

**Comment by eval-exec** [comment]
@getong 
Could you try, put the minimal configuration below in `/tmp/test.el`

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
;; and `package-pinned-packages`. Most users will not need or want to do this.
;;(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(package-initialize)
(setq-default use-package-always-ensure t)
(fido-vertical-mode t)
(use-package rg
             )


(use-package super-hint
             :vc (:url "https://github.com/eval-exec/super-hint.el"
                       :branch "main")
             :config
             (which-function-mode t)
             (super-hint-enable-rg)
             )
```
Then start emacs by: `emacs -Q -l /tmp/test.el`.

Then retry super-hint work on your machine?


I test the minimal configuration on my machine, it works.

![image](https://github.com/user-attachments/assets/14ffe03c-2f0f-4c22-b244-6c516dd02133)

**Comment by getong** [comment]
my mini config
```
(setq-default straight-base-dir (expand-file-name "var" user-emacs-directory)
              straight-repository-branch "develop"
              straight-vc-git-default-clone-depth '(1 single-branch)
              straight-build-dir (format "build-%s" emacs-version)
              ;; uncomment below to use packege.el, default use straight
              straight-check-for-modifications nil)
(setq straight-use-package-by-default t)


(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" straight-base-dir))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

;; need by super-hint
(use-package rg
  :straight t
  :commands rg
  :custom
  (rg-command-line-flags '("--no-heading" "--line-number" "--column"))
  (rg-group-result t)
  (rg-show-columns t)
  :config
  ;; C-c s, https://rgel.readthedocs.io/en/latest/usage.html
  (rg-enable-default-bindings)
  )

(use-package super-hint
  :straight (:host github :repo "eval-exec/super-hint.el")
  :config
  (require 'rg)
  (require 'super-hint-rg)
  (super-hint-enable-rg) ;; then M-x rg-project to enjoy super-hint

  (require 'super-hint-xref)
  (super-hint-enable-xref) ;; then M-x xref-find-references to enjoy super-hint
  (which-function-mode t)) ;; need open which-function mode
```
it works, it can jump to the right file.
<img width="1769" alt="image" src="https://github.com/user-attachments/assets/079d1815-54e4-4d2c-9b2f-71aa908d2560">

I will try to find the error

**Comment by eval-exec** [comment]
@getong If you find the error, please let me know the real reason. Thank you :blue_heart:

**Comment by getong** [comment]
my config makes this error, I disable it and delete it
```
;; ANSI & XTERM 256 color support
(use-package
 xterm-color
 :straight t
 :init (setenv "TERM" "xterm-256color") (setq comint-output-filter-functions (remove 'ansi-color-process-output comint-output-filter-functions)) (add-hook 'comint-preoutput-filter-functions 'xterm-color-filter)
 (add-hook
  'shell-mode-hook
  (lambda ()
    ;; Disable font-locking to improve performance
    (font-lock-mode -1)
    ;; Prevent font-locking from being re-enabled
    (make-local-variable 'font-lock-function)
    (setq font-lock-function #'ignore)))

 ;; For eshell
 (with-eval-after-load 'esh-mode
   (add-hook 'eshell-before-prompt-hook (lambda () (setq xterm-color-preserve-properties t)))
   (add-to-list 'eshell-preoutput-filter-functions 'xterm-color-filter)
   (setq eshell-output-filter-functions (remove 'eshell-handle-ansi-color eshell-output-filter-functions)))

 ;; For compilation buffers
 (setq compilation-environment '("TERM=xterm-256color"))
 (defun my-advice-compilation-filter (f proc string)
   (funcall f
            proc
            (if (eq major-mode 'rg-mode) ; compatible with `rg'
                string
              (xterm-color-filter string))))
 (advice-add 'compilation-filter :around #'my-advice-compilation-filter) (advice-add 'gud-filter :around #'my-advice-compilation-filter))
```

Thanks very much
