### ISSUE TITLE
Using minor modes instead of disable/enable functions

### ISSUE THREAD

**Issue by krisbalintona** [eval-exec/super-hint.el#8]
Currently, super-hint has specific enable and disable functions to add/remove its functionality (i.e. `super-hint-enable-rg`, `super-hint-disable-rg`, `super-hint-enable-xref`, and `super-hint-disable-xref`). As far as *conventions nowadays* goes, wouldn't it be preferable to create globalized minor modes instead? E.g. a `super-hint-xref-mode` and `super-hint-rg-mode`. Effectively, users get the same control over what's enabled but without having to call a separate set of functions to enable versus disable. (Minor modes are also more discoverable for users.)

**Comment by eval-exec** [comment]
Great 👍

**Comment by eval-exec** [comment]
Are you interested in submitting a PR? :laughing:

**Comment by krisbalintona** [comment]
> Are you interested in submitting a PR? :laughing:

Sure thing!

**Comment by krisbalintona** [comment]
Just submitted a PR. This should be good now.
